language: golang

go:
  - 1.4

env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"


install:
  - go get github.com/vanng822/accesslog
  - go get github.com/vanng822/r2router
  - go get github.com/vanng822/recovery
  - go get github.com/unrolled/render
  - go get github.com/stretchr/testify/assert

script:
  - go test -v
